### ISSUE TITLE
it has a conflict with the obsidian web browser plugin

### ISSUE THREAD

**Issue by fred1357944** [royxue/obsidian-things3-sync#1]
Thank you for develop this great plugini but it has a conflict with the obsidian web browser plugin https://github.com/Trikzon/obsidian-web-browser.

**Comment by royxue** [comment]
@fred1357944 
Could you provide more information about conflict?

**Comment by royxue** [comment]
I checked that plugin, it didnt have much documents within README, so I guess the problem might be it open the things3 in the browser tab? instead of the things3 app?

**Comment by royxue** [comment]
@fred1357944 
I tried install the plugin u mentioned, but it failed on my Obsidian.

Think the solution should be done in that plugin, because this things3 sync plugin use the standard Things3 URL schema(https://culturedcode.com/things/support/articles/2803573/), this is a common way of app communication on mac I think.

It seems the problems was caused by **web browser** plugin add hook to capture every window.open event but didnt do enough regex checking maybe. I think it's not good to capture all url-like string there, should add some bypass rules.
